# Redirect Netlify default domain → your main .in domain
[[redirects]]
  from = "https://imprakhartripathi.netlify.app/*"
  to = "https://imprakhartripathi.in/:splat"
  status = 301
  force = true

# Redirect www → root domain
[[redirects]]
  from = "https://www.imprakhartripathi.in/*"
  to = "https://imprakhartripathi.in/:splat"
  status = 301
  force = true
